# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntucourt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'managed': False, 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
    ]
